### ISSUE TITLE
Error when CombineAxes is false

### ISSUE THREAD

**Issue by poonesh** [3ptscience/steno3dmat#11]
![screen shot 2017-03-23 at 2 55 19 pm](https://cloud.githubusercontent.com/assets/18725251/24272495/35978e6e-0fe3-11e7-94c0-1038d03bbb9e.png)
![screen shot 2017-03-23 at 3 20 27 pm](https://cloud.githubusercontent.com/assets/18725251/24272498/37f841ee-0fe3-11e7-84bc-ccc413e0ab9c.png)

**Comment by fwkoch** [comment]
@poonesh - the reason this is erroring is because converting a figure without combining axes creates an array of multiple projects:

<img width="347" alt="screen shot 2017-03-24 at 12 32 08 pm" src="https://cloud.githubusercontent.com/assets/9453731/24308563/0cf8d91c-108e-11e7-859d-bc557e960977.png">

The real issue here is the nonsense error message...

**Comment by fwkoch** [comment]
Closed by #13
