### ISSUE TITLE
Z ordering issue in surface peak example (example1)

### ISSUE THREAD

**Issue by poonesh** [3ptscience/steno3dmat#27]
![image-matlab-surface](https://cloud.githubusercontent.com/assets/18725251/25113572/a45f7218-23b5-11e7-93ed-57e407ebc8bf.png)
images do not match

**Comment by poonesh** [comment]
this issue occurs for example2 and example4 of surface examples

**Comment by fwkoch** [comment]
Thanks for this @poonesh - I think this is a bug in the `steno3d.core.Surface.plot` function because the final version on steno3d.com is the correct ordering - it matches how the actual peaks function should look:

<img width="518" alt="screen shot 2017-04-18 at 10 09 06 am" src="https://cloud.githubusercontent.com/assets/9453731/25140958/3b0fa692-241f-11e7-87ec-87eb788b3abd.png">

**Comment by fwkoch** [comment]
Fixing the z order here broke it elsewhere. This needs more work - surface example3:

<img width="1037" alt="screen shot 2017-04-18 at 4 46 38 pm" src="https://cloud.githubusercontent.com/assets/9453731/25156248/b0b857f4-2456-11e7-99e8-95a1bbbd92e2.png">

**Comment by fwkoch** [comment]
The underlying problem here is that the matlab client expects steno3d to respect `ZOrder` on `Mesh2DGrid`, but it does not; it simply assumes `'c'` ordering. Built-in `'f'` ordering must be reversed.

**Comment by bsmithyman** [comment]
It doesn't respect the ordering? I thought that was fully functional last time we checked it (the "change the ordering" issue, when we went from `f` to `c` by default). Presumably something has changed?
If so, we may need to look to "old" projects, which IIRC are still in `f` order. Maybe I am missing something?

**Comment by fwkoch** [comment]
Thanks @bsmithyman - This flexibility exists for grid _data_ but not grid _z-values_.

- v0.1.x of the python client assumed both data and z are 'f' ordered. Since upload version is saved, this assumption still persists for old projects.
- v0.2.0 and greater of the python client allow data to specify 'f' or 'c', but assume z is 'c' ordered.

The matlab client allowed specifying 'c' or 'f' for z as well, but this was not respected. Now functionality matches the python client (and the current backend support).

Of course, this isn't great because 'f' ordering is more natural for matlab, but I think the nice plotting functions help abstract away a bit of this idiosyncrasy...

**Comment by fwkoch** [comment]
This should be resolved by #36
